<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>   
</head>
<body>
    <form action="<?php echo $action ?>" method="POST">
        <input type="text" placeholder="Wartość do przeliczenia [PLN -> USD]" />
        <input type="submit" value="przelicz" />
    </form>
    
    <?php echo $test; ?>
</body>
</html>
